(* generated by tools/latex2ocaml.py from `eq:crustos` -- do not edit.

   uses: crustos_prims.ml

   Every definition below is one the equation makes, in its braces
   or after `where`; every contract is one of its two theorems. *)

(* the model's fields are naturals *)
let natural c = cur c >= 0 && n c >= 0 && ticks c >= 0

let eq_i c = ((cur c) <= (n c))

let rank c = (if (n c) <= (cur c) then 0 else (n c) - (cur c))

let cond s = ((cur s) < (n s))

(* step = fun k ih s -> ih E: E is what one pass does *)
let step s = (if (cond s) then (pass s) else s)
  [@@requires natural s && eq_i s] [@@ensures natural result && eq_i result]

(* sched: Nat.rec with the identity at 0 -- a fold that applies `step` (rank c) times *)
let rec sched_loop1 k s = if k <= 0 then s else sched_loop1 (k - 1) (step s)
  [@@requires natural s && eq_i s] [@@ensures natural result && eq_i result] [@@variant k]
let sched c = sched_loop1 (rank c) c
  [@@requires natural c && eq_i c] [@@ensures natural result && eq_i result]

let run c = (tick (sched (tick c)))
  (* the state layer: the invariant survives the composition, for every state *)
  [@@requires natural c && eq_i c] [@@ensures natural result && eq_i result]

(* the routing layer: never longer than its input *)
let routing_layer ns us = (accepted ns us)
  [@@ensures List.length result <= (List.length (split us 44))]
